config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/mine', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'  # 클릭하면 대신 요청을 보냄
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'    # callback을 받는 친구
  end

  root 'movies#index'
  resources :movies do
    member do    # id까지 포함
      post '/comments' => 'movies#create_comment'
    end
    collection do
      delete '/comments/:comment_id' => 'movies#destroy_comment'
      patch '/comments/:comment_id' => 'movies#update_comment'
      get '/search_movie' => 'movies#search_movie'
    end
    # collection do
    #   get '/test' => 'movies#test_collection'
    # end
  end
  
  post '/uploads' => 'movies#upload_image'
  
  get '/likes/:movie_id' => 'movies#like_movie'
 # post '/movies/:movie_id/comments' => 'movies#comments'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :js_authenticate_user!, only: [:like_movie, :create_comment, :update_comment, :destroy_comment]
  before_action :authenticate_user!, except: [:index, :show, :search_movie]  # 둘 빼고 로그인한 유저만 보기가능
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :create_comment]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.page(params[:page])
    # respond_to do |format|  # html, js가 왔을때 각각 응답을 다르게 줄수 있다.
    #   format.html
    #   format.js
    # end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @user_likes_movie = Like.where(user_id: current_user.id, movie_id: @movie.id).first if user_signed_in?
    #@comment = Comment.all.reverse
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_movie
    p params
    # 현재 유저와 params에 담긴 movie간의 좋아요 관계를 설정한다.
    # 만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우-> 해당 Like 인스턴스 삭제
    # 새로 누른 경우 -> 좋아요 관계 설정
    @like = Like.where(user_id: current_user.id, movie_id: params[:movie_id]).first
    if @like.nil?
      @like = Like.create(user_id: current_user.id, movie_id: params[:movie_id])
    else
      @like.destroy
    end
    puts @like.frozen? #이메소드로 새로만든건지, 삭제를 한건지 알수있다.
    # @like.frozen? # @like.destroy처럼 삭제된경우 에는 사용하지못하도록 얼어있어.
    # -> true 라면 좋아요취소된친구
    
    # 현재 유저와 params에 담긴 movie간의 좋아요 관계를 설정한다.
    # Like.create(user_id: current_user.id, movie_id: params[:movie_id])

    puts "좋아요 설정 끝"
  end
  
  def create_comment
    # @movie = Movie.find(params[:id])
    @comment = Comment.create(user_id: current_user.id, movie_id: @movie.id, contents: params[:contents])
    # @movie.comments.new(user_id: current_user.id).save  #위에의 축약형
  end
  
  def destroy_comment
    @comment = Comment.find(params[:comment_id]).destroy
  end
  
  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update(contents: params[:contents])
  end
  
  def search_movie
    #원래는 이 액션명과 일치하는 js파일을 찾아서 data를 보내줌
    #Then, 다른 파일로 보내주어야 할때는 이렇게 쓰면 내가 원하는 js파일로 보낼수 있다. 
    
    respond_to do |format|
      if params[:q].strip.empty? 
        format.js {render 'no content'}
      else
        @movies= Movie.where("title LIKE ?", "#{params[:q]}%")  # 첫글자만 일치하고 뒤(%)는 아무거나
        format.js {render 'search_movie'}
      end
    end

    # if params[:q].strip.empty? 
    #   render nothing: true # 아무 응답없음
    # end
    # @movies = Movie.where("title LIKE ?", "#{params[:q]}%") 
  end
  
  def upload_image
    @image = Image.create(image_path: params[:upload][:image])  # hash 형태라서..
    render json: @image
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :director, :actor, :description, :image_path)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title ,class: "form-control" %>
  </div>
  
  <div class="form-group">
  <%= f.label :genre %>
  <%= f.text_field :genre ,class: "form-control" %>
  </div>
  
  <div class="form-group">
  <%= f.label :director %>
  <%= f.text_field :director ,class: "form-control" %>
  </div>
  
  <div class="form-group">
  <%= f.label :actor %>
  <%= f.text_field :actor ,class: "form-control" %>
  </div>
  
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description , 'data-provider': :summernote %>
  </div>

  <div class="form-group">
  <%= f.label :image_path %>
  <%= f.file_field :image_path ,class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/create_comment.js.erb
$('.comment-list').prepend(`
  <li class="comment-<%= @comment.id%> list-group-item d-flex justify-content-between">
      <span class="comment-detail-<%=@comment.id%>"><%= @comment.contents %></span>
      <div>
          <button data-id="<%=@comment.id %>" class="btn btn-warning text-white edit-comment">수정</button>
          <button data-id="<%=@comment.id %>" class="btn btn-danger destroy-comment">삭제</button>
      </div>
  </li>`);
$('.comment-contents').val('');
alert("댓글이 등록되었습니다.");

app/views/movies/destroy_comment.js.erb
alert("댓글이 삭제되었습니다.");
$('.comment-<%= @comment.id %>').remove();
//$(this).parent().remove();  this를 못가져와서 여기서 못씀

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1 id="title">Movies</h1>
<input type="text" class="form-control movie-title">
<div class="recomm-movie d-flex justify-content-start row">
</div>
<hr>
<div id="title" class="row">
<% @movies.each do |movie| %>
<div class="card col-md-4">
  <img class="card-img-top" src="<%= movie.image_path.thumb.url%>" alt="<%= movie.title %>">
  <div class="card-body">
    <h5 class="card-title" data-id="3" ><span><%= movie.title %></span></h5>
    <p class="card-text">Genre: <%= movie.genre %></p>
    <p class="card-text">Main Actor: <%= movie.actor %></p>
    <p class="card-text">Director: <%= movie.director %></p>
    <%= link_to "영화 정보보기", movie_path(movie) ,class: 'btn btn-primary'%>
  </div>
</div>
<% end %>
</div>
<br>
<%= paginate @movies, theme: 'twitter-bootstrap-4' %>

<%= link_to 'New Movie', new_movie_path %>

<hr>
<% if user_signed_in? %>
<!-- 로그인 된 상태 -->
<%= current_user.email %>
<%= link_to "로그아웃", destroy_user_session_path, method: "delete" %>
<% else %>
<!-- 로그아웃 된 상태 -->
<%= link_to "로그인", new_user_session_path %>
<% end %>

<!-- 자바스크립트 -->
 <script>
   $(document).on('ready', function(){
     $('.movie-title').on('keyup', function(){  //이벤트 바꿔가면서 확인해보자
       $('.recomm-movie').html('');  // 검색하고 나서 지웠을 때 정보 사라지도록
       var title=$(this).val();
       $.ajax({
         url: '/movies/search_movie',
         data: {
           q: title
         }
       })
     })
   });
 
// func2;
// var func1 = function(){
//   alert("하위~1");
//   // 선언되기 이전에 사용할 수 없다.
// }
// func1;
// function func2(){
//   alert("하위~2");
//   // 2. 함수 선언식
//   //선언되기 이전에도 사용할 수 있다.
// }

// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover", func2); // func2() : 이건 함수 실행, 함수명만 적어야 함수 등록

// var btn2 = document.getElementsByClassName("btn")[1];
// btn2.onmouseover =func1;  //함수 이름만 적어줘야 함수가 정상적으로 등록됨

// 먼저 선언되어 있던 함수를 이벤트 핸들러로 사용할 경우
// 함수 이름만 적어서 사용한다.
// 함수이름() <- 이 형태는 함수의 실행을 의미한다.

// 버튼(요소)에 마우스를 오버(이벤트)했더니(이벤트 리스너)
// 그 위에 있던 글자(요소)들이 갑자기 이상한 글자로 변해버린다(이벤트핸들러).

// var index =1;
// var text = document.getElementsByClassName("card-title")[index]
// var btn = document.getElementsByClassName("btn")[index];

// btn.addEventListener("mouseover", function(){
// var title = document.getElementsByClassName("card-title")[index];
// console.dir(title);
// title.innerText = "Don't touch me!!!!!!!"; //마우스를 올렸을때 title이 바뀜
// });

// btn.addEventListener("mouseout", function(){
//   var title = document.getElementsByClassName("card-title")[index];
//   title.innerText = text;
// });
// // 3. 익명함수

// 버튼(요소)에 마우스를 올리면(이벤트, 이벤트 리스너)
// 해당버튼(요소)의 class가 btn btn-danger로 변함(이벤트 핸들러)
// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover", function(){
//   btn.setAttribute("class", "btn btn-danger ");
// })
// btn.addEventListener("mouseout", function() {
//   btn.setAttribute("class", "btn btn-primary")
// })
</script>

app/views/movies/like_movie.js.erb
var like_count = parseInt($('.like-count').text());  //문자열이기때문에 숫자로 바꿔주어야 count가능

console.log(like_count);
if(<%= @like.frozen? %>){
    alert("좋아요 취소");
    like_count = like_count - 1;
    $('.like').html(`좋아요( <span class='like-count'>${like_count}</span> )`).addClass("btn-info").removeClass("btn-warning text-white");
} else {
    alert("좋아요 설정됐쩡");
    like_count = like_count + 1;
    $('.like').html(`좋아요 취소( <span class='like-count'>${like_count}</span> )`).addClass("btn-warning text-white").removeClass("btn-info");
}

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search_movie.js.erb
console.log("찾음");
$('.recomm-movie').html(`
<% @movies.each do |movie| %>
<span class="badge badge-primary"><%= movie.title %></span>&nbsp;&nbsp; 
<% end %>
`); 
// 검색된 title이 모두 찍혀야한다. @movies는 배열형태이므로 반복문 사

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<hr>
<p><%= simple_format(@movie.description) %></p> <!-- 브라우저가 인식할 수 있는 html tag로 바꿈 -->
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<hr>

<% if @user_likes_movie.nil? %>
<button class="btn btn-info like">좋아요 (<span class="like-count"><%=@movie.likes.count%></span>)</button>
<% else %>
<button class="btn btn-warning like text-white">좋아요 취소 (<span class="like-count"><%=@movie.likes.count%></span>)</button>
<% end %>
<hr>

<form class="text-right comment">
    <input class="form-control comment-contents">
    <input type="submit" value="댓글쓰기" class="btn btn-primary">
</form>
<hr>
<h3>댓글</h3>
<ul class="list-group comment-list">
  <!--<li class="list-group-item">Cras justo odio</li>-->
  <!-- 기존에 등록되어 있는 댓글 출력하기 -->
  <% @movie.comments.reverse.each do |comment|%>  
  <li class="comment-<%= comment.id%> list-group-item d-flex justify-content-between">
      <span class="comment-detail-<%=comment.id%>"><%= comment.contents %></span>
      <div>
          <button data-id="<%=comment.id %>" class="btn btn-warning text-white edit-comment">수정</button>
          <button data-id="<%=comment.id %>" class="btn btn-danger destroy-comment">삭제</button>
      </div>
  </li>
  <% end %>
</ul>
<hr>
<script>
//document가 다 준비된(load) 다음 동작해라 
//html보다 js가 먼저 작동할 위험이 사라짐(항상 여기에 넣기)
$(document).on('ready',function(){
    $('.like').on('click', function(){  //클래스로 좋아요 버튼 찾기
        console.log("like!!!"); 
        $.ajax({
           url: '/likes/<%= @movie.id %>' 
        });
    })  
    $('.comment').on('submit', function(e) {
        e.preventDefault();   
        var comm = $('.comment-contents').val();
        console.log(comm);
        //data가 여기로 넘어감
        $.ajax({  
           url: "/movies/<%= @movie.id %>/comments", 
           method: 'POST',
           data: {
               contents: comm
           }
        });
    })
    $(document).on('click', '.destroy-comment', function(){  //다시한번 reload!!하려고 document
        console.log("destroyed!!!");
        var comment_id = $(this).attr('data-id'); 
        //$(this).data('id');  //바로 위랑 똑같음
        $.ajax({
            url: "/movies/comments/" + comment_id,
            method: "delete"
        })
    });
    $(document).on('click','.edit-comment', function(){
        // var detail= $('.comment-detail').text();
        // console.log('detail');   이렇게 하면 댓글들이 전부합쳐서 나옴
        if ($('.update-comment').length == 0) {
        var comment_id = $(this).data('id');
        var edit_comment = $(`.comment-detail-${comment_id}`);
        var contents = edit_comment.text().trim();  //trim : 앞뒤공백 제거!
        edit_comment.html(`
        <input type="text" value="${contents}" class="form-control edit-comment-${comment_id}">`);
        $(this).text("확인").removeClass("edit-comment btn-warning").addClass("update-comment btn-dark");
        } else {
        alert("수정이 불가합니다.");
        }
    });
    
    $(document).on('click', '.update-comment', function(){
        console.log("update");
        var comment_id = $(this).data('id');
        var comment_form = $(`.edit-comment-${comment_id}`);
        $.ajax({
            url: "/movies/comments/" +comment_id,
            method: "patch",
            data: {
                contents: comment_form.val()
            }
        })
    });
});  

</script>

app/views/movies/update_comment.js.erb
alert("수정완료");
var edit_comment = $('.comment-detail-<%= @comment.id %>');
edit_comment.html('<%= @comment.contents %>');  //수정한 내용을 집어넣어줌
$('.update-comment').text("수정").removeClass("update-comment btn-dark").addClass("edit-comment btn-warning");